### PR TITLE
Use scalacheck-xml generators

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by armanbilge** [comment]
I'm impressed this is working, isn't it get tripped up between scala-xml 1.x and 2.x?

**Comment by armanbilge** [comment]
Ah, interesting. sbt won't raise eviction warnings in the `Test` scope it seems. If I move the dep to the `Compile` scope it gets angry as I expect.
```
sbt:root> scalaXml1/evicted
[error] stack trace is suppressed; run last scalaXml1 / evicted for the full output
[error] (scalaXml1 / evicted) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error]         * org.scala-lang.modules:scala-xml_2.13:2.1.0 (early-semver) is selected over 1.3.0
[error]             +- org.http4s:http4s-scala-xml-1_2.13:0.23-4e5a42f-20220622T052319Z-SNAPSHOT (depends on 2.1.0)
[error]             +- org.typelevel:scalacheck-xml_2.13:0.1.0            (depends on 2.1.0)
[error]             +- org.scala-lang.modules:scala-xml_2.13:1.3.0        (depends on 1.3.0)
```

**Comment by rossabaker** [comment]
Oh, geez, I didn't even think about how this would cause an eviction problem.  I think this means tests will run against scala-xml-2 on classes that were compiled with scala-xml-1?  That means we're testing the binary compatibility of our integration surface area, but not the semantics (like dropping comments) of scala-xml-1.  I think this PR is bad, but sharing those generators between projects is the point of scalacheck-xml!

**Comment by armanbilge** [comment]
Ooh right, good point. What we could do here is exclude the scala-xml dependency from the generators. But probably the more robust solution is to split scalacheck-xml into two artifacts just like we did here 😕

**Pull request merged**
