### PR TITLE
Rudimentary XML generator and round-trip test

### PR DESCRIPTION
**Pull request by rossabaker**
Generates `Elem` with scalacheck that we can check for round trip serialization to improve our test coverage.

We target XML 1.0, Fourth Edition, which is what the Xerces that comes with many (most?) JDKs deals with.

### CODE REVIEW

**Comment by rossabaker** [comment]
It would be better to focus on generating some more realistic XML.  But anyway:

```
  override def scalaCheckInitialSeed = "K_ELZQfI5d7H6Zd2g97PRbkK6gsdhkOnmHnv5vaYcxF="
Exception raised on property evaluation.
> ARG_0: <뜅벱號뷇:פ羯恻 駀J끎瞽ᾂ탞転匐:祯瞖="ꏘ˭袷ꊭ	"/>
> Exception: munit.ComparisonFailException: /home/runner/work/http4s-scala-xml/http4s-scala-xml/scala-xml/src/test/scala/org/http4s/scalaxml/ScalaXmlSuite.scala:66
65:        .as[Elem]
66:        .assertEquals(elem)
67:    }
values are not the same
=> Obtained
<뜅벱號뷇:פ羯恻 駀J끎瞽ᾂ탞転匐:祯瞖="ꏘ˭袷ꊭ "/>
=> Diff (- obtained, + expected)
-<뜅벱號뷇:פ羯恻 駀J끎瞽ᾂ탞転匐:祯瞖="ꏘ˭袷ꊭ "/>
+<뜅벱號뷇:פ羯恻 駀J끎瞽ᾂ탞転匐:祯瞖="ꏘ˭袷ꊭ	"/>
```

**Review by armanbilge — APPROVED** [review]
Didn't dig into all 400+ lines but seems good. 👍

**Comment by armanbilge** [comment]
Btw, it feels like this should be upstreamed, but where to. Wouldn't fs2-data-xml-scala also benefit from this?

**Comment by rossabaker** [comment]
I already created a discussion on scala-xml about that to see if there would be any interest.

**Comment by rossabaker** [comment]
Alright, this isn't perfect, but it's better coverage.  Can keep refining it.

**Pull request merged**
